# Autogenerated wrapper script for cfastcdr_jll for i686-w64-mingw32-cxx11
export libcfastcdr_1

using FastCDR_jll
JLLWrappers.@generate_wrapper_header("cfastcdr")
JLLWrappers.@declare_library_product(libcfastcdr_1, "libcfastcdr.dll")
function __init__()
    JLLWrappers.@generate_init_header(FastCDR_jll)
    JLLWrappers.@init_library_product(
        libcfastcdr_1,
        "bin\\libcfastcdr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
